# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a39e5cf859f4c107437d3d5bb3c45e111305eca71731d42a1e0557ae1b7affc2664dd128c3a6dc422759c2aadeedbb945cd1a14ea40ab6b5a41ea61191ef6c93

test:
  secret_key_base: 6d433431a768cc9a24942aaf42b99ddf341f934ffe6c4d6dc4980ee4002559d3cb250d8897dac7211fde1390f02d894e12c6301ad8445b5288ea28ed179ac31c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
